export default [
  {
    shipName: 'POLA ATLANTIC',
    year: '2010',
    deadweight: '33,466 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_atlantic.jpg'),
  },
  {
    shipName: 'POLA PACIFIC',
    year: '2011',
    deadweight: '33,413 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_pacific.jpg'),
  },
  {
    shipName: 'POLA INDIAN',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_indian.jpg'),
  },
  {
    shipName: 'POLA LADOGA',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_ladoga.JPG'),
  },
  {
    shipName: 'POLA ONEGA',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_onega.jpg'),
  },
  {
    shipName: 'POLA UGLICH',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_uglich.jpg'),
  },
  {
    shipName: 'POLA MUROM',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_murom.jpg'),
  },
  {
    shipName: 'POLA PALEKH',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_palekh.jpg'),
  },
  {
    shipName: 'POLA ANISIA',
    year: '2006',
    deadweight: '46,412 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_atlantic.jpg'),
  },
  {
    shipName: 'POLA ILARIA',
    year: '2010',
    deadweight: '37,495 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/pola_atlantic.jpg'),
  },
  {
    shipName: 'POLA AUGUSTA',
    year: '2008',
    deadweight: '32,271 mt',
    flag: 'Russia',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/ship2.png'),
  },
  {
    shipName: 'HANZE GDANSK',
    year: '2013',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/HANZE_GDANSK.jpg'),
  },
  {
    shipName: 'HANZE GOTEBORG',
    year: '2013',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/hanze_gotenberg.jpg'),
  },
  {
    shipName: 'HANZE GENDT',
    year: '2011',
    deadweight: '34,613 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/hanze_gendt.jpg'),
  },
  {
    shipName: 'HANZE GENUA',
    year: '2015',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/hanze_genua.jpg'),
  },
  {
    shipName: 'INTERLINK ABILITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/interlink_levity.jpg'),
  },
  {
    shipName: 'INTERLINK ACTIVITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/interlink_activity.jpg'),
  },
  {
    shipName: 'INTERLINK SAGACITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/INTERLINK_SAGACITY.jpg'),
  },
  {
    shipName: 'NORDTIGRIS',
    year: '2015',
    deadweight: '37,964 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    photo: require('./../../../_assets/images/ships/NORDTIGRIS.jpg'),
  },
];
