export const transport = [
  {
    id: 0,
    shipName: 'POLA ATLANTIC',
    year: '2010',
    deadweight: '33,466 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 1,
    shipName: 'POLA PACIFIC',
    year: '2011',
    deadweight: '33,413 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 2,
    shipName: 'POLA INDIAN',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 3,
    shipName: 'POLA LADOGA',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 4,
    shipName: 'POLA ONEGA',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 5,
    shipName: 'POLA UGLICH',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 6,
    shipName: 'POLA MUROM',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 7,
    shipName: 'POLA PALEKH',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 8,
    shipName: 'POLA ANISIA',
    year: '2006',
    deadweight: '46,412 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 9,
    shipName: 'POLA ILARIA',
    year: '2010',
    deadweight: '37,495 mt',
    flag: 'Malta',
    type: 'sea',
  },
  {
    id: 10,
    shipName: 'POLA AUGUSTA',
    year: '2008',
    deadweight: '32,271 mt',
    flag: 'Russia',
    type: 'sea',
  },
  {
    id: 11,
    shipName: 'HANZE GDANSK',
    year: '2013',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    type: 'sea',
  },
  {
    id: 12,
    shipName: 'HANZE GOTEBORG',
    year: '2013',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    type: 'sea',
  },
  {
    id: 13,
    shipName: 'HANZE GENDT',
    year: '2011',
    deadweight: '34,613 mt',
    flag: 'The Netherlands',
    type: 'sea',
  },
  {
    id: 14,
    shipName: 'HANZE GENUA',
    year: '2015',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    type: 'sea',
  },
  {
    id: 15,
    shipName: 'INTERLINK ABILITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    type: 'sea',
  },
  {
    id: 16,
    shipName: 'INTERLINK ACTIVITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    type: 'sea',
  },
  {
    id: 17,
    shipName: 'INTERLINK SAGACITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    type: 'sea',
  },
  {
    id: 18,
    shipName: 'NORDTIGRIS',
    year: '2015',
    deadweight: '37,964 mt',
    flag: 'Malta',
    type: 'sea',
  },
];

export const supply = [];

export const consctruct = [];
