export default [
  {
    id: 0,
    shipName: 'POLA ATLANTIC',
    year: '2010',
    deadweight: '33,466 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship1.png'),
  },
  {
    id: 1,
    shipName: 'POLA PACIFIC',
    year: '2011',
    deadweight: '33,413 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship2.png'),
  },
  {
    id: 2,
    shipName: 'POLA INDIAN',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship3.png'),
  },
  {
    id: 3,
    shipName: 'POLA LADOGA',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship4.png'),
  },
  {
    id: 4,
    shipName: 'POLA ONEGA',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship5.png'),
  },
  {
    id: 5,
    shipName: 'POLA UGLICH',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship6.png'),
  },
  {
    id: 6,
    shipName: 'POLA MUROM',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship7.png'),
  },
  {
    id: 7,
    shipName: 'POLA PALEKH',
    year: '2014',
    deadweight: '37,667 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship8.png'),
  },
  {
    id: 8,
    shipName: 'POLA ANISIA',
    year: '2006',
    deadweight: '46,412 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship9.png'),
  },
  {
    id: 9,
    shipName: 'POLA ILARIA',
    year: '2010',
    deadweight: '37,495 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship1.png'),
  },
  {
    id: 10,
    shipName: 'POLA AUGUSTA',
    year: '2008',
    deadweight: '32,271 mt',
    flag: 'Russia',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship2.png'),
  },
  {
    id: 11,
    shipName: 'HANZE GDANSK',
    year: '2013',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship3.png'),
  },
  {
    id: 12,
    shipName: 'HANZE GOTEBORG',
    year: '2013',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship4.png'),
  },
  {
    id: 13,
    shipName: 'HANZE GENDT',
    year: '2011',
    deadweight: '34,613 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship5.png'),
  },
  {
    id: 14,
    shipName: 'HANZE GENUA',
    year: '2015',
    deadweight: '34,735 mt',
    flag: 'The Netherlands',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship6.png'),
  },
  {
    id: 15,
    shipName: 'INTERLINK ABILITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship7.png'),
  },
  {
    id: 16,
    shipName: 'INTERLINK ACTIVITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship8.png'),
  },
  {
    id: 17,
    shipName: 'INTERLINK SAGACITY',
    year: '2014',
    deadweight: '38,500 mt',
    flag: 'Marshall',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship9.png'),
  },
  {
    id: 18,
    shipName: 'NORDTIGRIS',
    year: '2015',
    deadweight: '37,964 mt',
    flag: 'Malta',
    imo: 9489417,
    prevData: 'none',
    portOfRegistry: 'VALLETTA',
    typeOfVessel: 'BULKER',
    technicalOperator: 'INOK N.V. Verbindings - Oostkaai, 5-7, B-2000, Antwerpen, Belgium',
    commercialOperator: 'POLA MARIS NV on behalf of POLA MARITIME LONDON TOWER NOORDERPLAATS 9 B-2000 Antwerpen TEL +32 3 727 15 15 FAX +32 3 727 15 19',
    builder: 'Shandong Baibuting Shipbuilding',
    dateDelivered: 'DEC 2010',
    lengthOverAll: '180,00 m',
    lengthBetweenPerpendiculars: '176,75 m',
    extremeBreadth: '30,00 m',
    mouldedDepth: '14,70 m',
    type: 'sea',
    category: 'transport',
    photo: require('./../_assets/images/ships/ship1.png'),
  },
];
